name: CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
env:
  CSV_URL: "MLproject/train_pca.csv"

permissions:
  contents: write  # Allow GitHub Actions to push changes to the repository
  actions: write   # If necessary for specific actions that require more permissions

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
 
      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
 
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
      
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local
      
      # Setup Git LFS
      - name: Set up Git LFS
        run: |
           git config --global user.name ${{ secrets.username }}
           git config --global user.email ${{ secrets.email }}
           git lfs install
           git lfs track "mlruns/**"
           git add .gitattributes
           git commit -m "Track large files in mlruns with Git LFS" || true
           git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
           git config --global user.name ${{ secrets.USERNAME }}
           git config --global user.email ${{ secrets.EMAIL }}
           git add -f mlruns/
           git commit -m "Save mlruns from CI run" || true
           git push origin main
