name: CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
env:
  CSV_URL: "https://raw.githubusercontent.com/brianajiks123/latihan-version-control-mlflow-2/refs/heads/main/MLproject/train_pca.csv"

permissions:
  contents: write  # Allow GitHub Actions to push changes to the repository
  actions: write   # If necessary for specific actions that require more permissions

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Debug: List files
      - name: List project files
        run: ls -R

      # Download dataset
      - name: Download train_pca.csv
        run: |
          curl -L "$CSV_URL" -o train_pca.csv

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn

      # Run script
      - name: Run modelling script
        run: |
          python MLproject/modellingopt.py

      # Setup Git LFS
      - name: Set up Git LFS
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Save MLflow tracking output
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main
